//! **The launcher icon, emitted from the walk** (bl-0b31): Android's adaptive
//! icon takes a `VectorDrawable`, which is XML text — so the app's mark ships
//! as a derivation of [`super::mark`] rather than as a committed PNG the leak
//! gate would (rightly) refuse to read.
//!
//! **One source, and a test that says so.** The two files under
//! `android/app/src/main/res/drawable/` are generated by the two functions
//! below and pinned byte-for-byte by this module's test — the same
//! two-direction discipline the leak fixtures keep: the asset must match the
//! walk, and the walk must still emit an asset. Move a constant in `super`
//! and the test fails naming the file that has to be regenerated.
//!
//! **The geometry is Android's own** (adaptive icons): a 108×108 viewport
//! whose central 72×72 is the safe zone, so the unit square maps to that
//! square at an 18-unit offset. The mark's furthest ink is a node circle at
//! `END_R + NODE_R` from the centre — 0.446 of the unit square, so 64.2 units
//! across — which sits inside the 66-unit circle every launcher mask keeps.
//! Nothing here re-decides a shape: the traces are the walk's own sampled
//! points, the lune its own ribs, a disc two half-arcs, and the hues the
//! walk's own bytes.

use super::{Hue, Shape};

/// The viewport, the safe square inside it, and where that square starts.
const VIEWPORT: f32 = 108.0;
const SAFE: f32 = 72.0;
const INSET: f32 = 18.0;

/// The foreground layer: the mark itself, on transparency.
pub fn foreground() -> String {
    let mut body = String::new();
    for shape in super::mark() {
        body.push_str(&match &shape {
            Shape::Trace { path, width, fill } => stroked(&polyline(path), *fill, width * SAFE),
            Shape::Lune { ribs, fill } => {
                let mut points: Vec<(f32, f32)> = ribs.iter().map(|rib| rib.out).collect();
                points.extend(ribs.iter().rev().map(|rib| rib.back));
                filled(&format!("{} Z", polyline(&points)), *fill)
            }
            Shape::Disc {
                cx,
                cy,
                radius,
                fill,
            } => filled(&disc(*cx, *cy, *radius), *fill),
        });
    }
    document(&body)
}

/// The background layer: the void the mark's own pupil is filled with, full
/// bleed, because a launcher's mask crops this layer and a smaller shape
/// would show the system's ground through the corners.
pub fn background() -> String {
    document(&filled(
        &format!("M0,0 H{VIEWPORT:.0} V{VIEWPORT:.0} H0 Z"),
        super::VOID_DEEP,
    ))
}

/// The `<vector>` around one layer's paths.
fn document(body: &str) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
         <!-- Generated from the mark's own walk (yog_android::icon::drawable).\n\
         \x20    Do not edit: `src/icon/drawable.rs`'s test pins this file. -->\n\
         <vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n\
         \x20   android:width=\"{VIEWPORT:.0}dp\"\n\
         \x20   android:height=\"{VIEWPORT:.0}dp\"\n\
         \x20   android:viewportWidth=\"{VIEWPORT:.0}\"\n\
         \x20   android:viewportHeight=\"{VIEWPORT:.0}\">\n\
         {body}</vector>\n"
    )
}

/// A stroked path — the walk names a trace by its centreline and width, and
/// so does this: round caps and joins are what a stroker does with a sampled
/// arc, which is what `shell::mark` asks egui for.
fn stroked(data: &str, fill: Hue, width: f32) -> String {
    format!(
        "\x20   <path android:pathData=\"{data}\"\n\
         \x20       android:strokeColor=\"{}\"\n\
         \x20       android:strokeWidth=\"{width:.3}\"\n\
         \x20       android:strokeLineCap=\"round\"\n\
         \x20       android:strokeLineJoin=\"round\" />\n",
        hex(fill)
    )
}

/// A filled path.
fn filled(data: &str, fill: Hue) -> String {
    format!(
        "\x20   <path android:pathData=\"{data}\"\n\
         \x20       android:fillColor=\"{}\" />\n",
        hex(fill)
    )
}

/// A circle, in the one primitive a `VectorDrawable` has for it: two
/// half-arcs that close on themselves.
fn disc(cx: f32, cy: f32, radius: f32) -> String {
    let (x, y) = at((cx - radius, cy));
    let across = 2.0 * radius * SAFE;
    let r = radius * SAFE;
    format!(
        "M{x:.3},{y:.3} a{r:.3},{r:.3} 0 1,0 {across:.3},0 a{r:.3},{r:.3} 0 1,0 -{across:.3},0 Z"
    )
}

/// The walk's points as a move-and-lines path.
fn polyline(path: &[(f32, f32)]) -> String {
    path.iter()
        .enumerate()
        .map(|(index, point)| {
            let (x, y) = at(*point);
            let verb = if index == 0 { 'M' } else { 'L' };
            format!("{verb}{x:.3},{y:.3}")
        })
        .collect::<Vec<String>>()
        .join(" ")
}

/// The unit square, placed in the safe square inside the viewport.
fn at(point: (f32, f32)) -> (f32, f32) {
    (point.0.mul_add(SAFE, INSET), point.1.mul_add(SAFE, INSET))
}

/// A straight-alpha hue as Android writes one — **always all four bytes**.
/// Dropping the alpha when it is `FF` would be a second spelling for the one
/// case that happens to be every hue in the walk today, and the day one gains
/// an alpha it would be a silently opaque colour instead. One arm, no branch,
/// and `#AARRGGBB` is a form every Android colour attribute reads.
fn hex(fill: Hue) -> String {
    let [red, green, blue, alpha] = fill;
    format!("#{alpha:02X}{red:02X}{green:02X}{blue:02X}")
}

#[cfg(test)]
mod tests;
